name: HyperMerchant
main: grokswell.hypermerchant.HyperMerchantPlugin
version: 1.6.2-dev
description: Inventory menu to be used with HyperConomy shops and NPC trait for Citizens2.
author: Grokswell
authors: [Grokswell] 
database: false
depend: [HyperConomy]
softdepend: [Citizens]
commands:
   shopmenu:
      description: Must be standing in shop to use. Browse a HyperConomy shop's inventory. Buy and Sell with ease.
      usage: /shopmenu
      permission: hypermerchant.menu
      permission-message: You do not have permission to use command /shopmenu.
      aliases: [smenu,storemenu]
   remotemenu:
      description: Browse a HyperConomy shop's inventory. Buy and sell with ease.
      usage: /remotemenu [shopname]
      permission: hypermerchant.remote
      permission-message: You do not have permission to use command /remotemenu.
      aliases: [rmenu]
   managemenu:
      description: Must be standing in shop to use. Edit your player shop inventory with ease.
      usage: /managemenu (shopname)
      permission: hypermerchant.menu
      permission-message: You do not have permission to use command /managemenu.
      aliases: [mmenu,manmen]
   rmanage:
      description: Must specify a shop name. Edit your player shop inventory with ease.
      usage: /managemenu (shopname)
      permission: hypermerchant.rmanage
      permission-message: You do not have permission to use command /rmanage.
      aliases: [rman]
   remoteshoplist:
      description: List shop names in a format that can be used with /remotemenu.
      usage: /remoteshoplist
      permission: hypermerchant.remote
      permission-message: You do not have permission to use command /remoteshoplist.
      aliases: [rslist]
   onduty:
      description: Toggle a shop owner between being onduty or offduty.
      usage: /onduty
      permission: hypermerchant.onduty
      permission-message: You do not have permission to use command /onduty.
      aliases: [offduty]
   closeshop:
      description: Permanently close the shop you have rented.
      usage: /closeshop
      permission: hypermerchant.closeshop
      permission-message: You do not have permission to use command /closeshop.
      aliases: [shopclose]
   fireclerk:
      description: Fire the clerk that you have currently selected.
      usage: /fireclerk
      permission: hypermerchant.fireclerk
      permission-message: You do not have permission to use command /fireclerk.
      aliases: [hfire]
   hmerchant:
      description: Set the properties of the currently selected hypermerchant npc.
      usage: "\n§4/hmerchant §csetshop §a[shopname] §6[--id idnum] §e- Set shop of selected hypermerchant.
  	    Set to shop player is standing in if no [shopname] argument provided.\n\n
  	    §4/hmerchant §coffduty §6[--id idnum] §e- Toggle npc in and out of offduty mode.\n\n
  	    §4/hmerchant §crental §6[--id idnum] §e- Toggle npc as having a shop for rent. npc must already be assigned to a shop.\n\n
  	    §4/hmerchant §cforhire §6[--id idnum] §e- Toggle npc as being for hire. npc must not be assigned to a shop.\n\n
  	    §4/hmerchant §ccomission §a[percent] §6[--id idnum] §e- Set the Merchant's comission, where percent is a number between 0 and 100.\n\n
        §4/hmerchant §cgreeting §a[welcome message] §6[--id idnum] §e- Set text NPC says upon player interaction.
  	    Leave [welcome message] argument empty for no text.\n\n
        §4/hmerchant §cfarewell §a[goodbye message] §6[--id idnum] §e- Set text NPC says upon player closing menu.
  	    Leave [goodbye message] argument empty for no text.\n\n
        §4/hmerchant §cdenial §a[deny message] §6[--id idnum] §e- Set text NPC says when player is not permitted to use a shop.
  	    Leave [deny message] argument empty for no text.\n\n
  	    §4/hmerchant §cclosed §a[closed message] §6[--id idnum] §e- Set text NPC says to a player when NPC is off duty.
  	    Leave [closed message] argument empty for no text.\n\n
  	    §4/hmerchant §clist §e- List information of all existing hypermerchant NPCs.\n\n
  	    §4/hmerchant §cinfo §6[--id idnum] §e- Show information of a single hypermerchant."
      permission: hypermerchant.manage
      permission-message: You do not have permission to use command /hmerchant.
      aliases: [hmerch]
   clerk:
      description: Manage you clerk NPCs.
      usage: "\n§4/clerk §csetshop §a[shopname] §6[--id idnum] §e- Set shop of selected clerk.
  	    Set to shop player is standing in if no [shopname] argument provided.\n\n
  	    §4/clerk §chire §a[name] §6[npc type] §6[-s shopname] §e- Hire a clerk to work in the shop you are standing in. Or use -s flag to hire for any shop.
  	    The new clerk will spawn in one corner of the your shop\n\n
  	    §4/clerk §cfire §6[--id idnum] §e- Fire the selected clerk, or specify clerk to fire by ID.\n\n
  	    §4/clerk §cselect §a[name or idnum] §e- Select one of your clerk npcs.\n\n
  	    §4/clerk §coffduty §6[--id idnum] §e- Toggle clerk in and out of offduty mode.\n\n
  	    §4/clerk §ctp §6[--id idnum] §e- Teleport a clerk to your current position.\n\n
        §4/clerk §cgreeting §a[welcome message] §6[--id idnum] §e- Set text clerk says upon player interaction.
  	    Leave [welcome message] argument empty for no text.\n\n
        §4/clerk §cfarewell §a[goodbye message] §6[--id idnum] §e- Set text clerk says upon player closing menu.
  	    Leave [goodbye message] argument empty for no text.\n\n
        §4/clerk §cdenial §a[deny message] §6[--id idnum] §e- Set text clerk says when player is not permitted to use a shop.
  	    Leave [deny message] argument empty for no text.\n\n
  	    §4/clerk §cclosed §a[closed message] §6[--id idnum] §e- Set text clerk says to a player when clerk is off duty.
  	    Leave [closed message] argument empty for no text.\n\n
  	    §4/clerk §clist §e- List information of all your clerk NPCs.\n\n
  	    §4/clerk §ctype §a[npc type] §6[--id idnum] §e- Set your clerk to a different type of NPC."
      permission: hypermerchant.clerk
      permission-message: You do not have permission to use command /clerk.
      aliases: [hclerk]
    
permissions:
   hypermerchant.*:
      description: Gives access to all HyperMerchant commands
      children:
         hypermerchant.menu: true
         hypermerchant.remote: true
         hypermerchant.npc: true
         hypermerchant.manage: true
         hypermerchant.clerk: true
         hypermerchant.onduty: true
   hypermerchant.menu:
      description: Allow use of the /shopmenu command.
      default: true
   hypermerchant.npc:
      description: Allow interaction with hypermerchant npc.
      default: true
   hypermerchant.fireclerk:
      description: Allow use of the /fireclerk command.
      default: true
   hypermerchant.closeshop:
      description: Allow use of the /closeshop command.
      default: true
   hypermerchant.onduty:
      description: Allow use of the /onduty command.
      default: true
   hypermerchant.remote:
      description: Allow use of the /remotemenu command.
      default: op
   hypermerchant.rmanage:
      description: Allow use of the /rmanage command.
      default: op
   hypermerchant.manage:
      description: Allow use of the /hmerchant command.
      default: op
   hypermerchant.clerk:
      description: Allow use of the /clerk command.
      default: op
   creative.hypermerchant:
      description: Allow player to purchase,sell, and manage their shop while in creative mode. Be extremely careful with this permission.
      default: false
